### ISSUE TITLE
Prima attivita'

### ISSUE THREAD

**Issue by GiulioUmbrella** [GiulioUmbrella/LAB1-TOS#1]
Prima attività creata nel primo laboratorio di TOS

La schermata è uguale per tutti gli issue, per differenziarla devo usare per forza i label.

**Comment by TommasoAzz** [comment]
Wow sto commentando!

**Comment by GiulioUmbrella** [comment]
Cazzo abbiamo fatto un errore

**Comment by GiulioUmbrella** [comment]
Ok l'errore e' stato brillantemente risolto
