### ISSUE TITLE
BAU

### ISSUE THREAD

**Issue by GiulioUmbrella** [GiulioUmbrella/LAB1-TOS#2]

**Comment by WenXiaowei** [comment]
miao,

"Non andare in sbattimento"

**Comment by TommasoAzz** [comment]
Andrebbe documentato il fatto che è il verso del cane in Dog.java

**Comment by GiulioUmbrella** [comment]
Saremo superorganizzati

**Comment by WenXiaowei** [comment]
Alessandro sa organizzarsi benissimo.
